export { CourseSelector } from "./CourseSelector"
export { StatsCard } from "./StatsCard"
export { ContentPanel } from "./ContentPanel"
export { COURSE_CONFIG, TYPE_STYLES } from "./curriculumData"
export type { CourseModule, CourseProject, Course, CourseConfig } from "./curriculumData"
