export { default as ajeful } from './ajeful.jpg';
export { default as debrotto } from './debrotto.jpg';
export { default as mehedi } from './mehedi.jpg';
export { default as mithun } from './mithun.jpg';
export { default as neyemur } from './neyemur.jpg';
export { default as ruponpaul } from './rupon_paul.jpeg';
export { default as rohan } from './rohan.jpeg';
export { default as puspita } from './puspita.jpg';
export { default as sakin } from './sakin.jpeg';
