"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _EnrollmentSection from './EnrollmentSection.bones.json'
import _EnrollmentFixed from './EnrollmentFixed.bones.json'
import _banner_section from './banner-section.bones.json'
import _maintenance_page from './maintenance-page.bones.json'

configureBoneyard({"color":"#e5e5e5","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#333333"})

registerBones({
  "EnrollmentSection": _EnrollmentSection,
  "EnrollmentFixed": _EnrollmentFixed,
  "banner-section": _banner_section,
  "maintenance-page": _maintenance_page,
})
